// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
const go = {
  "main": {
    "App": {
      /**
       * CancelDownload
       * @returns {Promise<void>} 
       */
      "CancelDownload": () => {
        return window.go.main.App.CancelDownload();
      },
      /**
       * ClientFileExists
       * @returns {Promise<boolean>}  - Go Type: bool
       */
      "ClientFileExists": () => {
        return window.go.main.App.ClientFileExists();
      },
      /**
       * DeleteProxy
       * @param {number} arg1 - Go Type: int64
       * @returns {Promise<Error>}  - Go Type: error
       */
      "DeleteProxy": (arg1) => {
        return window.go.main.App.DeleteProxy(arg1);
      },
      /**
       * DownloadClientFile
       * @returns {Promise<void>} 
       */
      "DownloadClientFile": () => {
        return window.go.main.App.DownloadClientFile();
      },
      /**
       * GetLogs
       * @param {number} arg1 - Go Type: int64
       * @returns {Promise<Array<Log>>}  - Go Type: []*main.Log
       */
      "GetLogs": (arg1) => {
        return window.go.main.App.GetLogs(arg1);
      },
      /**
       * GetProxies
       * @returns {Promise<Array<Proxy>>}  - Go Type: []main.Proxy
       */
      "GetProxies": () => {
        return window.go.main.App.GetProxies();
      },
      /**
       * InsertProxy
       * @param {Proxy} arg1 - Go Type: *main.Proxy
       * @returns {Promise<Error>}  - Go Type: error
       */
      "InsertProxy": (arg1) => {
        return window.go.main.App.InsertProxy(arg1);
      },
      /**
       * OpenGithub
       * @returns {Promise<void>} 
       */
      "OpenGithub": () => {
        return window.go.main.App.OpenGithub();
      },
      /**
       * RunProxy
       * @param {number} arg1 - Go Type: int64
       * @returns {Promise<Error>}  - Go Type: error
       */
      "RunProxy": (arg1) => {
        return window.go.main.App.RunProxy(arg1);
      },
      /**
       * StopProxy
       * @param {number} arg1 - Go Type: int64
       * @returns {Promise<Error>}  - Go Type: error
       */
      "StopProxy": (arg1) => {
        return window.go.main.App.StopProxy(arg1);
      },
      /**
       * UpdateProxy
       * @param {Proxy} arg1 - Go Type: *main.Proxy
       * @returns {Promise<Error>}  - Go Type: error
       */
      "UpdateProxy": (arg1) => {
        return window.go.main.App.UpdateProxy(arg1);
      },
    },
  },

};
export default go;
